

name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest  
                             

    env:
      Solution_Name: JSharp.sln                          
      Test_Project_Path: JSharp.Tests/JSharp.Tests.csproj 

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x 
      
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Restore the solution
      run: msbuild ${{ env.Solution_Name }} /t:Restore /p:Configuration=${{ matrix.configuration }}

    - name: Build the solution
      run: msbuild ${{ env.Solution_Name }} /p:Configuration=${{ matrix.configuration }}

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test ${{ env.Test_Project_Path }} --configuration ${{ matrix.configuration }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Build artifacts
        path: |
          **/bin/${{ matrix.configuration }}/*
